### ISSUE TITLE
Update for use with react native 0.26

### ISSUE THREAD

**Issue by alexanderniebuhr** [d-a-n/react-native-modal-picker#11]
Hello can u please change the code in index.js so the component uses 

**animationType**

Prop instead of

**animated**

Prop

Thanks

**Comment by paulailincai** [comment]
Hi, I also believe Portal = require('react-native/Libraries/Portal/Portal.js'); has been deprecated.

**Comment by rajkissu** [comment]
I've sent a PR #12 to support RN0.26, remove the Portal dependency, and fix the animationType prop issue.

**Comment by orhanmaden** [comment]
@rajkissu Thanks for the code!

I copied your code and also had the remove the rebound import from index.js.

A tip for other devs:
To make the sample work replace the imports with:
```
import React, { Component } from 'react';

import {
    View,
    TextInput,
    AppRegistry
} from 'react-native';
```

**Comment by rajkissu** [comment]
@d-a-n can you merge the PR?

**Comment by ararog** [comment]
@orhanmaden I believe you can just fork and make the changes on this fork while the author doesn't merge your PR, so people will be able to use your changes without wait for a new official version.

**Comment by orhanmaden** [comment]
@ararog I don't fork and share code that I can't give support for in the future.

Feel free to fork, apply the fixed and share the repository. These are the steps involved:
1. Fork the code
2. Apply the PR of @rajkissu : https://github.com/d-a-n/react-native-modal-picker/pull/12/commits
3. Remove the rebound import from index.js

And off course share the link.

**Comment by ararog** [comment]
Yes, i know how to do it, and no, it isn't a solution for all problems, otherwise I would ask author write access in this repository, the idea is have this fork while the author cant apply any PR instead of wait the day when it happens, so for those that are in a rush please create a fork, do the changes and update the package.json file.

**Comment by d-a-n** [comment]
Sorry guys for the delay. Its merged now. @rajkissu Thanks again.
